# Generated by Django 4.0.4 on 2022-10-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesMater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mst_categories',
            },
        ),
        migrations.CreateModel(
            name='EventsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('event_title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('open_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('site_open_time', models.TimeField()),
            ],
            options={
                'db_table': 'mst_events',
            },
        ),
        migrations.CreateModel(
            name='GenresMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mst_genres',
            },
        ),
        migrations.CreateModel(
            name='PlacesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('station', models.CharField(max_length=255)),
                ('place_image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('map', models.URLField()),
            ],
            options={
                'db_table': 'mst_places',
            },
        ),
        migrations.CreateModel(
            name='TimeTablesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mst_time_tables',
            },
        ),
        migrations.CreateModel(
            name='TicketsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('sale_start_date', models.DateTimeField()),
                ('sale_end_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_event_site.eventsmaster')),
            ],
            options={
                'db_table': 'mst_tickets',
            },
        ),
        migrations.CreateModel(
            name='NewsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('open_date', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_event_site.eventsmaster')),
            ],
            options={
                'db_table': 'mst_news',
            },
        ),
        migrations.CreateModel(
            name='ImagesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_event_site.eventsmaster')),
            ],
            options={
                'db_table': 'mst_image',
            },
        ),
        migrations.CreateModel(
            name='GroupArtistsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_event_site.genresmaster')),
            ],
            options={
                'db_table': 'mst_groups',
            },
        ),
        migrations.CreateModel(
            name='ArtistsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_event_site.categoriesmater')),
            ],
            options={
                'db_table': 'mst_artists',
            },
        ),
    ]
